version: '3'
services:

  mysql57:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=mysql-pw-123
    volumes:
      - mysql-data:/var/lib/mysql

  myphp71:
    image: myphp71
    depends_on:
      - mysql57
    volumes:
      - /data:/data
    ports:
      - "8080:80"

volumes:
  mysql-data:
