version: '2'
services:
    web:
        image: nginx:alpine
        ports:
            - "8081:80"
        volumes:
            - ./webroot:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/site.conf
        links:
            - php8
            - php7
            - php5
    php8:
        image: php:8-fpm-alpine
        volumes:
            - ./webroot:/var/www/html
    php7:
        image: php:7-fpm-alpine
        volumes:
            - ./webroot:/var/www/html
    php5:
        image: php:5-fpm-alpine
        volumes:
            - ./webroot:/var/www/html
